vich_uploader:
    db_driver: orm

    mappings:
       produits_images:
           uri_prefix: /images/produit
           upload_destination: '%kernel.project_dir%/public/images/produits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
